services:
  frontend:
    build: ./frontend
    ports: 
      - "8070:80"
    networks:
      - "app-network"
  backend:
    build: ./backend
    ports: 
      - "8080:8080"
    networks:
      - "app-network"
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres:alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: contactsdb
      POSTGRES_USER: atesh
      POSTGRES_PASSWORD: atesh
    networks:
      - "app-network"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U atesh -d contactsdb"]
      interval: 5s
      timeout: 5s
      retries: 5
networks:
  app-network: